mauricioszabo/atom-chlorine

src/chlorine/repl.cljs
Update `clojure.test` support functions to reflect `current-editor` being changed to `atom/current-editor`.
=> Fix clojure.test support (current-editor moved)

CHANGELOG.md, package-lock.json, src/chlorine/providers_consumers/autocomplete.cljs, src/chlorine/repl.cljs, src/chlorine/ui/connection.cljs, src/chlorine/ui/console.cljs, src/chlorine/ui/inline_results.cljs
On this PR:
* Fixes autocomplete error: https://github.com/mauricioszabo/atom-chlorine/issues/26
* Fixes backpressure error: https://github.com/mauricioszabo/repl-tooling/issues/7
* When we close the REPL console, we now disconnect from Socket REPLs
=> Backpressure error fix, and small ffixes on autocomplete and Console Tab

src/chlorine/core.cljs, src/chlorine/repl.cljs
Adds two commands: `inspect-block` and `inspect-top-block` that behave like `evaluate-block` and `evaluate-top-block` respectively, but also `submit` the code and value to REBL, if it is on the classpath.
=> Adds support for Cognitect's REBL

src/chlorine/repl.cljs
The idea here is that if the requested file path looks like Windows -- `<drive>:/path/to/file.ext` -- but the REPL reports the user directory as looking like Linux -- starting with a bare `/` -- then assume the REPL is running on WSL on the Windows machine and map the drive to a mount point as `/mnt/<drive>/path/to/file.ext`
This won't help Atom on Windows connecting to a non-WSL REPL that is running remotely on Mac/Linux but that usage can't really be solved in the general case -- but it won't make it worse either.
This won't affect Atom running on Mac/Linux -- nor Atom on Windows connecting to a Windows REPL.
=> Support Atom on Windows talking to REPL on WSL

src/chlorine/ui/connection.cljs
Currently, in the socket connection dialog, when a text field comes in to focus, the text is not selected (highlighted).  This commit is an attempt to have the text be selected on focus instead.
=> Select network text field content on focus

src/chlorine/repl.cljs
It turns out the `datafy` call is unnecessary and interferes with `Var` navigation in the latest version of REBL.
=> Fix REBL integration

CHANGELOG.md, styles/chlorine.less
- Fix `#js` tagged literal
- Shadow-CLJS can now evaluate multiple forms
- Fix stacktraces on ClojureScript
- Removed "shadow" on exception on CLJS (conflicts with light theme)
- Fixed link spacing on renderer
=> Small fixes

src/chlorine/providers_consumers/status_bar.cljs
The string `CLJ connected (simple refresh)` takes up a *lot* of real estate unnecessarily. `CLJ (simple)` is as informative but frees up a lot of space for other packages to use!
=> Take up less space in status bar

CHANGELOG.md, package.json
- Fix goto var definition failing when the var was defined evaluating blocks, or with load-file
=> Release v0.1.9

README.md
Maybe change `source-for-var` suggestion to `ctl-, S`?
=> Keymap has duplicate c entry

src/chlorine/ui/connection.cljs
This enables tabbing between fields in the "Connect to Socket REPL" window.
=> enable tabbing in connection window

CHANGELOG.md, package-lock.json, package.json, src/chlorine/providers_consumers/autocomplete.cljs
- Fixed some error with autocomplete in CLJS (https://github.com/mauricioszabo/atom-chlorine/issues/85)
- Added experimental features with a config to control
- Disabled editing on Console tab (https://github.com/mauricioszabo/atom-chlorine/issues/79)
- Changed defaults for auto-reload projects	- Changed defaults for auto-reload projects
- Rendering correctly the ratio (like `1/2`)
- Fixed load-file on non-saved or non-editor tabs (https://github.com/mauricioszabo/atom-chlorine/issues/75)	- Fixed load-file on non-saved or non-editor tabs (https://github.com/mauricioszabo/atom-chlorine/issues/75)
- To be able to support multiple NS on the same files and also to remove internal Atom's
API on detecting the current start/end forms, there's a new way to detect start/end
of forms. This affects …
=> Release v0.1.11

CHANGELOG.md, integration/clojure-test.js, package.json, scripts/ci-prepare-release, shadow-cljs.edn, src/chlorine/core.cljs, src/chlorine/repl.cljs, src/chlorine/state.cljs, src/chlorine/ui/console.cljs, src/chlorine/ui/inline_results.cljs
- Fixed InkConsole not opening (https://github.com/mauricioszabo/atom-chlorine/issues/93)
- Better evaluate-block and evaluate-top-block without using Atom API (still behind the experimental features)
- Commands "evaluate-selection", "evaluate-top-block" and "evaluate-block" without using Atom's APIs. They also are aware of reader symbols, so now `evaluate-block` over `'(+ 1 2 3)` will return a list, not run the function.
=> Release v0.1.12

CHANGELOG.md, package-lock.json, package.json
- Fixes problems when evaluating code that can't be compiled (https://github.com/mauricioszabo/atom-chlorine/issues/109)
- Fixes autocomplete crashing the editor
=> Release v0.2.2

CHANGELOG.md, package-lock.json, package.json
- Removed printing of `name.space=> ` on console for CLJS
- Fixes styling issues on console tab
- Fixed double-exception rendering on console tab
=> Release v0.2.1

scripts/setup
The setup script removes lib/main.js.  This change prevents that.
=> Do not remove main.js during setup

CHANGELOG.md, package-lock.json, package.json
- Fixed evaluation on CLR where it fails with "Unable to resolve symbol: str in this context"
- Load-file working on multiple REPLs
- Fixed UUIDs
=> Release 0.3.3

CHANGELOG.md, package-lock.json, package.json
- Some REPLs don't send a "disconnect" event when closing the socket, so we "simulate" a disconnect
- Fixed "Disconnected from REPLs" appearing twice
- Copy results to clipboard
=> Release v0.3.4

CHANGELOG.md, package-lock.json, package.json
- Fixed issues with "Copy to Clipboard"
- Removed old connection methods like "Connect Clojure Socket REPL" and "Connect ClojureScript REPL"
- Removed deprecated extension points
=> Release v0.3.5

CHANGELOG.md, package-lock.json, package.json
- Added specs on doc-for-var (https://github.com/mauricioszabo/atom-chlorine/issues/100)
- Fixed an issue with goto var definition where sometimes it wasn't able to find the var
=> Release 0.3.6

CHANGELOG.md, package-lock.json, package.json
- Fixed "get current var" when cursor is at the end of the variable
- Fixed warning messages connection to Shadow-CLJS when reagent is not present (https://github.com/mauricioszabo/atom-chlorine/issues/127)
=> Release v0.3.7

CHANGELOG.md, package-lock.json, package.json
- Fixed error when trying to execute a ClojureScript code when REPL is not clj-connected
- Fixed warnings when connecting to ClojureScript without reagent
- First try to fix problem with autocomplete showing symbols on console tab (probably only on Windows)
=> Release v0.3.8

CHANGELOG.md, integration/Dockerfile, integration/chlorine-tests/shadow-cljs.edn, integration/chlorine-tests/test/chlorine/tests.cljs, package-lock.json, package.json, scripts/test
- Supporting Suitable for CLJS autocomplete
- When evaluating top-level, considers the parens before the cursor if the selection is on the end of the line
- Fixes for strange issues happening on evaluation of Clojure forms (sometimes, things were evaluating out-of-order or returning nil incorrectly)
- Migrated autocomplete tools to use promises, to avoid crashing the Atom editor in case of failures while autocompleting
- Fixed a bug on Autocomplete (when disconnecting the REPL and adding/removing Compliment, the autocomplete would still try to use/not use Compliment after connecting to REPL)
=> Release 0.4.3

CHANGELOG.md, package-lock.json, package.json
- Fixes "Attempting to call unbound fn: #'unrepl.core/write" (https://github.com/mauricioszabo/atom-chlorine/issues/158)
=> Release v0.4.11

CHANGELOG.md, package-lock.json, package.json, styles/chlorine.less
- Fixed issue with GOTO Var Definition when the current file's full path is too long.
=> Release v0.4.15

CHANGELOG.md, package-lock.json, package.json
- Faster nREPL messages parsing
- Load-file now prints the stacktrace when it fails to load
- Fixed paths on Windows, so goto var definition and clicking on stacktraces will work
=> Release v0.5.2

package-lock.json, package.json
- Loading tests on full refresh
- Fixed parsing of namespaces with metadata, and quotes (the kind you get when using clj-kondo)
=> Release 0.5.4

CHANGELOG.md, package-lock.json, package.json
- Fixed connection for other Clojure implementations like Clojerl, Joker, etc.
=> Release v0.6.1

CHANGELOG.md, package-lock.json, package.json
- Forward-finding namespaces if a NS form was not found before the cursor (fixes https://github.com/mauricioszabo/atom-chlorine/issues/193)
- Waiting for REPL results before forwarding new commands to the REPL (probably fixes https://github.com/mauricioszabo/atom-chlorine/issues/192)
- Autocomplete shows docstrings and arities when completing functions
=> Release v0.7.3

README.md
Update readme to reflect the change of 'inline-results:clear-all' into 'chlorine:clear-inline-results' in the keybindings example.
=> Readme: 'inline-results:clear-all' -> 'chlorine:clear-inline-results'

CHANGELOG.md, package-lock.json, package.json, shadow-cljs.edn, src/chlorine/ui/inline_results.cljs
- Fix on regexp printing
- Using another way to connect to Shadow-CLJS
- Implemented the new Websocket REPL of Shadow-CLJS (Remote API)
- For now, removed inspection of JS and resolving promises
-------
Will not publish this release so soon - if there are bugs, I'll probably not be able to fix then on a timely manner. If you want to try it, just clone this repository on your `~/.atom/packages` folder, rename `atom-chlorine` to just `chlorine`, and change to the branch `v0.8.0`.
=> Release v0.8.0

CHANGELOG.md, package-lock.json, package.json, src/chlorine/ui/inline_results.cljs
- Possibility of running Shadow-CLJS Remote API commands (see: https://github.com/mauricioszabo/repl-tooling/pull/83)
- Small fix on inline results, with Experimental Features, when saving a file with errors on Shadow-CLJS
=> Release v0.8.1

CHANGELOG.md, package-lock.json, package.json
- Support for resolving promises on Shadow Relay API
- `tap>` support for Shadow-CLJS Relay API
=> Release v0.8.2

CHANGELOG.md, package-lock.json, package.json
- Fixed defining functions with same name as `clojure.core` (fixes https://github.com/mauricioszabo/atom-chlorine/issues/214).
- Fixed clojure REPL not connecting on first try
- Interactive eval redirects STDOUT
=> Release v0.9.4

CHANGELOG.md, package.json, src/chlorine/ui/connection.cljs
Currently, chlorine pre-fills the connection port if it can find `/.shadow-cljs/socket-repl.port`.
I've added additional support for `.nrepl-port` if it exists (as generated by `lein repl`) and `.socket-repl-port`.
Let me know if you'd like it refactored (say, moving all the port-file logic into a separate fn).
=> Suggest port from .nrepl-port if exists

CHANGELOG.md
- Fixed issue detecting port from `.shadow-cljs/socket-repl.port` file on Windows
- Added support for detecting port from `.nrepl-port` and `.socket-repl-port` files
- Trying to fix issue https://github.com/mauricioszabo/atom-chlorine/issues/234
=> Release v0.10.3

CHANGELOG.md, package-lock.json, package.json
- Migrated most of Pathom code to a new project called Duck-REPLed
- Disabled clj-kondo statistics for now
- Fixed stacktraces in Clojerl
- Fixed Lumo REPL
- Source for var now works for ClojureScript with Shadow-CLJS
=> Release v0.12.0
