mauricioszabo/atom-chlorine

.gitignore
.gitmodules
project.clj
shadow-cljs.edn
src/clojure_plus/core.cljs
src/clojure_plus/features/refresh.cljs
src/clojure_plus/providers_consumers/autocomplete.cljs
src/clojure_plus/repl.cljs
src/clojure_plus/state.cljs
src/clojure_plus/ui/atom.cljs
src/clojure_plus/ui/connection.cljs
src/clojure_plus/ui/console.cljs
src/clojure_plus/ui/doc.cljs
src/clojure_plus/ui/inline_results.cljs

Some CLJS support, documentation, autocomplete, and CLJS evaluation.
Missing:

CLJS support

---

CHANGELOG.md
integration/clojure-test.js
package.json
scripts/watch
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/ui/connection.cljs
src/chlorine/ui/inline_results.cljs

In this PR:
* Capturing ClojureScript exceptions
* Stacktrace for CLJS when available
* Support for Lumo or Plank
* Autocomplete for Lumo (using lumo.repl/get-completions)
* Autodetection for auto-completion in Lumo or Generic

Better ClojureScript support

---

CHANGELOG.md
docs/developing.md
src/chlorine/core.cljs
src/chlorine/features/code.cljs
src/chlorine/repl.cljs
src/chlorine/ui/doc.cljs

Also, fixed some problems with Inline Evaluation: row number was being sent incorrectly to REPL.

GOTO definition

---

src/chlorine/core.cljs
src/chlorine/repl.cljs

* run-tests-in-ns -- run all tests in the current namespace
* run-test-for-var -- run the test whose name is under the cursor

Add support for clojure.test

---

src/chlorine/core.cljs
src/chlorine/repl.cljs

This may show a conflict with show source since it adds a new function in about the same place. Let me know if you want an updated PR after merging show source.

Add load file function

---

CHANGELOG.md
README.md
package.json
src/chlorine/features/code.cljs
src/chlorine/features/refresh.cljs
src/chlorine/repl.cljs
src/chlorine/ui/doc.cljs
src/chlorine/ui/inline_results.cljs

Goto var will open a readonly editor with the contents of a file inside a JAR.

Better GOTO var

---

shadow-cljs.edn

As per #39, here's an attempt.

Remove :source-paths and :dependencies from shadow-cljs.edn

---

src/chlorine/repl.cljs

Allow output for CLJS to be written to console
Also fixes rendering of `#js` tag, and when Shadow-CLJS fails to connect, error is returned to the user.

Output on CLJS

---

CHANGELOG.md
README.md
integration/clojure-test.js
src/chlorine/configs.cljs
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/ui/connection.cljs
src/chlorine/ui/console.cljs

This PR fixes https://github.com/mauricioszabo/atom-chlorine/issues/33 and https://github.com/mauricioszabo/atom-chlorine/issues/32.
The problem is that currently, Ink console has no way to detect it was closed, so I'm using a somewhat wrong way to detect.

Console Fixes

---

package.json
scripts/ci-prepare-release

Fix the last two version's bug

Release v0.1.5

---

.gitignore
CHANGELOG.md
lib/main.js
shadow-cljs.edn
src/chlorine/core.cljs
src/chlorine/repl.cljs

For some reason, Atom on OSX don't like the minified build...
Fixes https://github.com/mauricioszabo/atom-chlorine/issues/67

MacOSX fix

---

CHANGELOG.md
integration/clojure-test.js
package.json

- Fix GOTO definition
- Takes up less space on status bar

Release v0.1.8

---

CHANGELOG.md
package.json

One more error on ClojureScript's version bump...

Fixing autocomplete

---

CHANGELOG.md
package-lock.json
shadow-cljs.edn
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/state.cljs
src/chlorine/ui/connection.cljs
src/chlorine/ui/inline_results.cljs

Added a config for experimental and possibly buggy features to be turned on/off
Also fixes #75

Experimental features

---

CHANGELOG.md
package-lock.json
shadow-cljs.edn
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/state.cljs
src/chlorine/ui/connection.cljs
src/chlorine/ui/console.cljs
src/chlorine/ui/inline_results.cljs

Disable Console's editable text

---

README.md

Here is a PR as discussed in https://github.com/mauricioszabo/atom-chlorine/issues/91

Tweaks to keybinding docs in README

---

shadow-cljs.edn
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/state.cljs

Evaluation (still behind feature flag) is now using Rewrite-CLJS to detect start and end of forms.

Evaluation commands fixes

---

CHANGELOG.md
integration/clojure-test.js
shadow-cljs.edn
src/chlorine/core.cljs
src/chlorine/repl.cljs
src/chlorine/state.cljs
src/chlorine/ui/console.cljs
src/chlorine/ui/inline_results.cljs

Fix Ink Console not appearing

---

CHANGELOG.md
src/chlorine/core.cljs
src/chlorine/providers_consumers/autocomplete.cljs
src/chlorine/providers_consumers/status_bar.cljs
src/chlorine/repl.cljs
src/chlorine/ui/connection.cljs
styles/chlorine.less

Also, autocomplete with Compliment on CLJS

Multi target shadow-cljs

---

src/chlorine/repl.cljs
src/chlorine/ui/doc.cljs
src/chlorine/ui/inline_results.cljs
styles/chlorine.less

Remove double render of exceptions

---

CHANGELOG.md
README.md
integration/Dockerfile
integration/chlorine-tests/test/chlorine/tests.cljs
integration/chlorine-tests/test/chlorine/utils.cljc
package-lock.json
package.json
scripts/test
src/chlorine/core.cljs
src/chlorine/providers_consumers/autocomplete.cljs
src/chlorine/repl.cljs
src/chlorine/ui/connection.cljs

Related to: https://github.com/mauricioszabo/repl-tooling/pull/38

Detect REPL type

---

CHANGELOG.md
package-lock.json
package.json

- Fixed autocomplete error on dynamic vars (https://github.com/mauricioszabo/atom-chlorine/issues/132)
- Support for Clojerl
- Treating special windows chars on REPL output

Release v0.3.9

---

CHANGELOG.md
package-lock.json
package.json
src/chlorine/features/refresh.cljs

- Fixed test results and output not appearing on console

Release v0.4.1

---

src/chlorine/repl.cljs

Closes https://github.com/mauricioszabo/atom-chlorine/issues/139

Fix REBL integration

---

CHANGELOG.md
package-lock.json
package.json

- Fixed https://github.com/mauricioszabo/atom-chlorine/issues/139

Release 0.4.2

---

CHANGELOG.md
package-lock.json
package.json

- Autocomplete for Babashka
- Dropping Ink dependency

Release v0.4.7

---

CHANGELOG.md
package.json
src/chlorine/ui/inline_results.cljs

- Fix for CSS of Ink inline results, and some edge-cases that could throw exceptions

Release v0.4.9

---

CHANGELOG.md
package-lock.json
package.json
src/chlorine/ui/inline_results.cljs

Fixes https://github.com/mauricioszabo/atom-chlorine/issues/156

Release v0.4.10

---

CHANGELOG.md
package-lock.json
package.json

- Fixed connection with Babashka

Release 0.4.16

---

CHANGELOG.md
package.json
src/chlorine/configs.cljs

Release v0.5.0

---

CHANGELOG.md
package-lock.json
package.json

- Simple fix for nREPL on slower sockets
- (Possible) load-file fix

Release v0.5.1

---

CHANGELOG.md
package-lock.json
package.json

- Fixed paths on dar*win* systems

Release v0.5.3

---

CHANGELOG.md
src/chlorine/features/refresh.cljs
src/chlorine/repl.cljs

Fix https://github.com/mauricioszabo/atom-chlorine/issues/179

Fix refresh on save

---

CHANGELOG.md
package-lock.json
package.json

- Fixed core Clojerl exception
- Fixed saving file when Clojure is disconnected and auto-refresh is turned on (Fixes https://github.com/mauricioszabo/atom-chlorine/issues/179)
- More commands comming from Orchard:
- find-usages
- clojure-doc-for-var

Release V0.6.2

---

CHANGELOG.md
docs/extending.md
package-lock.json
package.json

- Performance improvement while parsing Clojure code
- Runnable config
- Fixed error trying to connect to ClojureScript socket REPLs

Release v0.7.0

---

CHANGELOG.md
package-lock.json
package.json
scripts/test

- Fix on `get-selection` for configs in ClojureScript

Release bump to v0.7.1

---

CHANGELOG.md
package-lock.json
package.json
src/chlorine/features/refresh.cljs
src/chlorine/ui/connection.cljs

- Fixed that tried to run refresh on EDN files
- Fix on `get-selection` for configs in ClojureScript
- Remove Ink
- Performance fixes on inline results, removed LOTS of memory leaks
- `editor/eval-and-render` now resolves as promises

Release v0.7.2

---

CHANGELOG.md
package-lock.json
package.json
scripts/test
src/chlorine/features/refresh.cljs

- Fixed refresh code not working

Release v0.7.4

---

CHANGELOG.md
package-lock.json
package.json
shadow-cljs.edn

- Adding custom tag `:div/clj` to render Clojure forms

Release v0.9.3

---

CHANGELOG.md
package-lock.json
package.json
shadow-cljs.edn

- Fixed nREPL code disconnecting when you send accents
- Fixed some undetectable var definitions on ClojureScript

Release v0.10.1

---

README.md
docs/quickstart.md

Just a little fix on some styling issues on Quickstart.

Reorganize quickstart md

---

package-lock.json
package.json

- Removed error on ClojureScript, with experimental features, for Browser targets

Release v0.10.4

---

CHANGELOG.md
package-lock.json
package.json

Release v0.10.6

---

.circleci/config.yml
CHANGELOG.md
integration/Dockerfile
package-lock.json
package.json
scripts/ci-prepare-release
scripts/ci-release

- Pathom resolvers are now customizable
- Go to var definition now works with namespaces
- Several fixes for clickable stacktraces in Clojure

Release v0.11.0

---

CHANGELOG.md
package.json

- Fixed goto var definition with CLJ-Kondo

Release bump to v0.11.1
